spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 9db07dc4cc669d471a8b
            client-secret: 721098547582734cbb73b0c7dcd3e960e1db9270
  data:
    cassandra:
      keyspace-name: main
      username: vRGlIgTXlLjseihNXcIEeiLP
      password: s0RhvNj2z9dTj_oMiYMJOmoWQG-RNgM0FqDOu0fp797tB9WzL9Kp1afNRtozkvPPij1eCF25iW7-IbQ4rUDAPMzqpiQFmGHoA-10,cA+c3ogvNYzaXah_WjW9zYnH4zo
      schema-action: create-if-not-exists
      request:
        timeout: 30s
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s

datadump.location:
  authors: /home/vladimir/dev/betterreads/betterreads-webapp/test-authors.txt
  works: /home/vladimir/dev/betterreads/betterreads-webapp/test-works.txt

datastax.astra:
  secure-connect-bundle: secure-connect.zip

astra.db:
  id: 4bcbb066-495f-4673-b1c7-cd031fdb266d-1
  region: westus2
  keyspace: main
  application.token: AstraCS:vRGlIgTXlLjseihNXcIEeiLP:374a5c65240c19a09d8ccd41952add0d956039caaec8cc5905ee50f523109e92
